(function(a){function b(){var b=a("<div>").addClass("browser"),c=a("<div>").addClass("browser-diolag"),d=a("<div>").addClass("browser-content"),e=a("<div>").addClass("browser-text"),f=a("<h3>").addClass("not-allowed").html("\u60a8\u7684\u6d4f\u89c8\u5668\u6682\u4e0d\u652f\u6301\u672c\u7f51\u7ad9"),g=a("<p>").addClass("recommed").html("\u63a8\u8350\u60a8\u4f7f\u7528\u4ee5\u4e0b\u6d4f\u89c8\u5668\u8fdb\u884c\u7ade\u62cd\uff1a"),h=a("<p>").addClass("allowed").html("Chrome\uff1b360\u5b89\u5168\u6d4f\u89c8\u5668\uff1bIE8\uff1bIE9\uff1bIE11\uff1bUC\u6d4f\u89c8\u5668\uff1b \u641c\u72d7\u6d4f\u89c8\u5668\uff1bFirefox\uff1bMicrosoft Edge\uff1bSafari"),
m=a("<input>").addClass("btn-cancel").attr({type:"button"}).val("\u5173\u95ed\u7f51\u7ad9");e.append(f);e.append(g);e.append(h);e.append(m);d.append(e);b.append(c);b.append(d);a(document.body).append(b);m.click(function(){var a=navigator.userAgent;-1!=a.indexOf("Firefox")||-1!=a.indexOf("Chrome")?window.location.href="about:blank":(window.opener=null,window.open("","_self"),window.close())})}(function(){var a=navigator.userAgent;-1<a.indexOf("compatible")&&-1<a.indexOf("MSIE")?(/MSIE (\d+\.\d+);/.test(a),
8>parseFloat(RegExp.$1)&&b()):-1>a.indexOf("Chrome")?b():-1>a.indexOf("Firefox")?b():-1>a.indexOf("Edge")?b():-1>a.indexOf("Safari")&&b()})();var c=document,d=a(".search-input"),e=function(a){var b=a.getAttribute("placeholder");""==a.defaultValue&&(a.value=b);a.onfocus=function(){if(a.value===b)this.value=""};a.onblur=function(){if(a.value==="")this.value=b}};if(!("placeholder"in c.createElement("input")))for(var c=0,g=d.length;c<g;c++){var f=d[c],h=f.getAttribute("placeholder");"text"===f.type&&
h&&e(f)}a.cookie_userinfo=function(b,c){a.ajax({type:"GET",url:"/caa-personal-ws/ws/0.1/login/mine",dataType:"json",cache:!1,async:!0,success:function(c){c&&c.userId&&(a.cookie("GLOBAL_ME_ID",c.userId,{path:"/"}),a.cookie("GLOBAL_ME_NICKNAME",c.userName,{path:"/"}),a.cookie("GLOBAL_ME_TYPE",c.userType,{path:"/"}));a.isFunction(b)&&b(c)},error:function(b){a.isFunction(c)&&c(b)}})};a.remove_userinfo=function(){a.removeCookie("GLOBAL_ME_ID",{path:"/"});a.removeCookie("GLOBAL_ME_NICKNAME",{path:"/"});
a.removeCookie("GLOBAL_ME_TYPE",{path:"/"})};a.logout=function(){a.ajax({type:"GET",url:"/caa-personal-ws/ws/0.1/logout",dataType:"json",cache:!1,async:!0,success:function(){a.remove_userinfo();window.location.href="/pages/user/login.html?redirect="+window.location.href},error:function(){a.remove_userinfo();window.location.href="/pages/user/login.html?redirect="+window.location.href}})};a.loadMailNum=function(){a.ajax({type:"GET",url:"/personal-ws/ws/0.1/inmail/num?state=0",dataType:"json",async:!0,
cache:!1,success:function(b){0==b?a(".mailNum").html(""):a(".mailNum").html(b).css("padding","0px 3px 2px")},error:function(){}})};a.changeMailState=function(){a.ajax({type:"get",url:"/personal-ws/ws/0.1/change/inmail/state",contentType:"application/json;charset=utf-8",dataType:"json",async:!0,success:function(){a(".mailNum").html("")},error:function(){}})}})(jQuery);
util={setlogo:function(){"true"==_resource.istest?($(".main-nav li .nav-sifa").hide(),$(".caa-logo").attr("src","/themes/images/testlogo.png"),$(".caa-red-logo").attr("src","/themes/images/logo-redtest.png"),$(".shop-test").attr("href",_resource.officialurl),$(".shop-official").attr("href",_resource.testurl+"/shop")):($(".main-nav li .nav-sifa").attr("href",_resource.sfurl).css("display","inline-block"),$(".caa-logo").attr("src","/themes/images/headbanner.png"),$(".caa-red-logo").attr("src","/themes/images/logo-red.png"),
$(".shop-test").attr("href",_resource.testurl),$(".shop-official").attr("href",_resource.officialurl+"/shop"))},getQueryString:function(a){a=RegExp("(^|&)"+a+"=([^&]*)(&|$)");a=window.location.search.substr(1).match(a);return null!=a?a[2]:null},IsPC:function(){for(var a=navigator.userAgent,b="Android;iPhone;SymbianOS;Windows Phone;iPad;iPod".split(";"),c=!0,d=0;d<b.length;d++)if(0<a.indexOf(b[d])){c=!1;break}return c},getvalue:function(a){a=RegExp("(^|&)"+a+"=([^&]*)(&|$)");a=window.location.search.substr(1).match(a);
return null!=a?a[2]:null},getIdFromUrl:function(){var a=window.location.toString(),b=a.lastIndexOf("/"),a=a.substring(b+1),b=a.lastIndexOf(".html");if(0<b){if(a=a.substring(0,b),null!=a)return a}else return a;return null},getdata:function(a,b,c,d,e,g,f){var h="&";-1==a.indexOf("?")&&(h="?");$.ajax({url:a+h+"time="+(new Date).getTime(),type:b,dataType:c,cache:d,async:e,success:g,error:f})},formatCurrency:function(a){if("0"==a)return"0";if(""==a||null==a||void 0==a)return"";for(var a=a.toString().replace(/\$|\,/g,
""),b=a==(a=Math.abs(a)),a=Math.floor(100*a+0.50000000001),a=(Math.floor(a)/100).toString(),c=a.split("."),a=c[0].length,d=c[0].length%3,e="";0<a;)0<a%3?(e+=c[0].substring(0,d)+",",a-=d):(e+=c[0].substring(d,d+3)+",",a-=3,d+=3);a=e.substring(0,e.length-1);a+=isNaN(c[1])?"":"."+c[1];return(b?"":"-")+a},formatNum:function(a){return a=a.toString().replace(/\$|\,/g,"")},changeMoneyToChinese:function(a){if("0"==a)return"\u96f6\u5143\u6574";var b="\u96f6\u58f9\u8d30\u53c1\u8086\u4f0d\u9646\u67d2\u634c\u7396".split(""),
c=["","\u62fe","\u4f70","\u4edf"],d=["","\u4e07","\u4ebf","\u5146"],e=["\u89d2","\u5206","\u6beb","\u5398"],g,f="";if(""==a)return"";a=parseFloat(a);if(1E15<=a)return"";if(0==a)return f=b[0]+"\u5143\u6574";a=a.toString();-1==a.indexOf(".")?g="":(g=a.split("."),a=g[0],g=g[1].substr(0,4));if(0<parseInt(a,10)){for(var h=0,l=a.length,i=0;i<l;i++){var j=a.substr(i,1),k=l-i-1,n=k/4,k=k%4;"0"==j?h++:(0<h&&(f+=b[0]),h=0,f+=b[parseInt(j)]+c[k]);0==k&&4>h&&(f+=d[n])}f+="\u5143"}if(""!=g){c=g.length;for(i=0;i<
c;i++)j=g.substr(i,1),"0"!=j&&(f+=b[Number(j)]+e[i])}""==f?f+=b[0]+"\u5143\u6574":""==g&&(f+="\u6574");return f},tranferTime:function(a,b,c,d){var a=parseInt(a),a=new Date(a),b=!b?a.getFullYear()+"\u5e74":"",e=!c?("0000"+a.getHours()).substring(("0000"+a.getHours()).length-2)+":"+("0000"+a.getMinutes()).substring(("0000"+a.getMinutes()).length-2):"",e=e+(!d&&!c?":"+("0000"+a.getSeconds()).substring(("0000"+a.getSeconds()).length-2):"");return b+("0000"+(a.getMonth()+1)).substring(("0000"+(a.getMonth()+
1)).length-2)+"\u6708"+("0000"+a.getDate()).substring(("0000"+a.getDate()).length-2)+"\u65e5 &nbsp;"+e},tranferTime2:function(a,b,c,d){if(!a)return"";a=parseInt(a);a=new Date(a);b=!b?a.getFullYear()+"-":"";c=!c?("0000"+a.getHours()).substring(("0000"+a.getHours()).length-2)+":"+("0000"+a.getMinutes()).substring(("0000"+a.getMinutes()).length-2):"";c+=d?":"+("0000"+a.getSeconds()).substring(("0000"+a.getSeconds()).length-2):"";return b+("0000"+(a.getMonth()+1)).substring(("0000"+(a.getMonth()+1)).length-
2)+"-"+("0000"+a.getDate()).substring(("0000"+a.getDate()).length-2)+" "+c},tranferTime3:function(a,b,c){if(!a)return"";var a=parseInt(a),d=new Date(a),a=d.getHours()+"\u5c0f\u65f6"+("0000"+d.getMinutes()).substring(("0000"+d.getMinutes()).length-2)+"\u5206",d=("0000"+d.getSeconds()).substring(("0000"+d.getSeconds()).length-2);return c?d+"\u79d2":b?a:""},tranferTime4:function(a){var b=parseInt(a)+"\u79d2";if(60<parseInt(a)){var c=parseInt(a)%60,d=parseInt(a/60),b=d+"\u5206"+c+"\u79d2";if(60<d){var d=
parseInt(a/60)%60,e=parseInt(parseInt(a/60)/60),b=e+"\u5c0f\u65f6"+d+"\u5206"+c+"\u79d2";24<e&&(e=parseInt(parseInt(a/60)/60)%24,b=parseInt(parseInt(parseInt(a/60)/60)/24)+"\u5929"+e+"\u5c0f\u65f6"+d+"\u5206"+c+"\u79d2")}}return b},tranferTime5:function(a,b,c){a=parseInt(a);a=new Date(a);b=!b?a.getFullYear()+"\u5e74":"";c=!c?("0000"+a.getHours()).substring(("0000"+a.getHours()).length-2)+":"+("0000"+a.getMinutes()).substring(("0000"+a.getMinutes()).length-2):"";return b+("0000"+(a.getMonth()+1)).substring(("0000"+
(a.getMonth()+1)).length-2)+"\u6708"+("0000"+a.getDate()).substring(("0000"+a.getDate()).length-2)+"\u65e5 &nbsp;"+c},changeToEmpty:function(a,b){return a?("string"!=typeof a&&$.each(a,function(c,d){if(null==d||void 0==d||"null"==d||"undefined"==d)d=b?b:"",a[c]=d}),a):b?b:""},formatMoney:function(a){var b=100*a+"";return b=1E10<=b?b.replace(/(\d{10}$)/,".$1").replace(/(.)([1-9]*)(0{1,}$)/,function(a,b,e,g){return!e&&0<g.length?"":b+e})+"<em class='f14'>\u4ebf</em>":1E6<=b?b.replace(/(\d{6}$)/,".$1").replace(/(.)([1-9]*)(0{1,}$)/,
function(a,b,e,g){return!e&&0<g.length?"":b+e})+"<em class='f14'>\u4e07</em>":a},transformNull:function(a){return!a&&("object"==typeof a||"undefined"==typeof a)?"":a},addingFn:function(a,b){a=parseFloat(a);b=parseFloat(b);if("number"!=typeof a||"number"!=typeof b)return"";var c,d;a.toString().split(".")[1]&&b.toString().split(".")[1]?(c=a.toString().split(".")[1].length,d=b.toString().split(".")[1].length,c=Math.pow(10,Math.max(c,d)),c=(a*c+b*c)/c):c=a+b;-1<c.toString().indexOf(".")&&(c=parseFloat(c).toFixed(2));
return c},addDate:function(a,b){var c=(new Date(a)).getTime(),c=new Date(c+864E5*b),d=c.getMonth()+1,e=c.getDate();return c.getFullYear()+"-"+(10>d?"0"+d:d)+"-"+(10>e?"0"+e:e)}};String.prototype.replaceSpace=function(){return this.replace(/(^\s{1,})|(\s{1,}$)|(\s{1,})/g,"")};util.setlogo();
