var user={islogin:function(){var a=user.info();return a&&a.userName?!0:!1},info:function(){var a={};$.ajax({type:"GET",url:"/caa-personal-ws/ws/0.1/login/mine",dataType:"json",cache:!1,async:!1,success:function(b){b&&b.userId&&($.cookie("GLOBAL_ME_ID",b.userId,{path:"/"}),$.cookie("GLOBAL_ME_NICKNAME",b.userName,{path:"/"}),$.cookie("GLOBAL_ME_TYPE",b.userType,{path:"/"}));a=b}});return a},name:function(){return $.cookie("GLOBAL_ME_NICKNAME")},id:function(){return $.cookie("GLOBAL_ME_ID")},type:function(){return $.cookie("GLOBAL_ME_TYPE")},
gologin:function(){user.islogin()||(window.location.href="/pages/user/login.html")},style:{unauth:function(a){var b=$("<div>").addClass("back-top");$(document.body).append(b);b.click(function(){$("html,body").animate({scrollTop:0})});var d=($(window).width()-1200)/2-60;b.css({right:d});1300>=$(window).width()&&b.css({right:0});$(".other-nav a").attr("href","/pages/user/login.html");return a?"true"==_resource.istest?'<div class="nologin-info"><a target="_blank" href="" class="float-left shop-test">\u8fdb\u5165\u6b63\u5f0f\u7248</a><p><a class="shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0\u6d4b\u8bd5\u7248</a><a href="/pages/user/register.html">\u514d\u8d39\u6ce8\u518c</a><a href="/pages/user/login.html?redirect='+
a+'">\u767b\u5f55</a></p></div>':'<div class="nologin-info"><a target="_blank" href="" class="float-left shop-test">\u8fdb\u5165\u6d4b\u8bd5\u7248</a><p><a class="shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0</a><a href="/pages/user/register.html">\u514d\u8d39\u6ce8\u518c</a><a href="/pages/user/login.html?redirect='+a+'">\u767b\u5f55</a></p></div>':"true"==_resource.istest?'<div class="nologin-info"><a target="_blank" href="" class="float-left shop-test">\u8fdb\u5165\u6b63\u5f0f\u7248 </a><p><a class="shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0\u6d4b\u8bd5\u7248</a><a href="/pages/user/register.html">\u514d\u8d39\u6ce8\u518c</a><a href="/pages/user/login.html">\u767b\u5f55</a></p></div>':
'<div class="nologin-info"><a target="_blank" href="" class="float-left shop-test">\u8fdb\u5165\u6d4b\u8bd5\u7248</a><p><a class="shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0</a><a href="/pages/user/register.html">\u514d\u8d39\u6ce8\u518c</a><a href="/pages/user/login.html">\u767b\u5f55</a></p></div>'},authed:function(){$(".other-nav a").attr("href","/pages/personal/home.html");var a=$("<div>").addClass("back-top");$(document.body).append(a);a.click(function(){$("html,body").animate({scrollTop:0})});
var b=($(window).width()-1200)/2-60;a.css({right:b});1300>=$(window).width()&&a.css({right:0});$(".J-container-title").html("");var a=$('<div class="login-info">'),b=$("<p>"),d=$('<a href="/pages/personal/home.html?showuse=4" class="tipnews" target="_blank"></a>').html('\u6d88\u606f<em class="mailNum"></em>'),e=$("<span>").addClass("user").html(user.name()),c=$("<em>").css("display","none");1E3==user.type()?c.append('<a href="/caa-oc/index.html" target="_blank" class="active"><s>\u7ba1\u7406\u4e2d\u5fc3</s></a>'):
($(".main-nav li:last").show(),c.append('<a href="/pages/personal/home.html?showuse=1" target="_blank" class="active"><s>\u4e2a\u4eba\u4e2d\u5fc3</s></a>'));var f=$("<a>").attr("href","javascript:void(0)").append("<s>\u9000\u51fa</s>").on("click",function(){$.logout()});e.hover(function(){$(this).children("em").show()},function(){$(this).children("em").hide()});c.append(f);e.append(c);"true"==_resource.istest?b.append('<a class="shop-link shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0\u6d4b\u8bd5\u7248</a>'):
b.append('<a class="shop-link shop-official" href="" target="_blank">\u62cd\u5356\u4f01\u4e1a\u540e\u53f0</a>');b.append(d);b.append(e);"true"==_resource.istest?a.append('<a class="float-left shop-test" target="_blank" href="" >\u8fdb\u5165\u6b63\u5f0f\u7248</a>'):a.append('<a class="float-left shop-test" target="_blank" href="" >\u8fdb\u5165\u6d4b\u8bd5\u7248</a>');a.append(b);return a}}};
(function(a,b){a.fn.headerStyle=function(){user.islogin()?user.name()?(a(this).append(user.style.authed(b.location.href)),a.loadMailNum(user.id())):a(this).html(user.style.unauth(b.location.href)):a(this).html(user.style.unauth(b.location.href));util.setlogo();a("head").append('<script>var _hmt = _hmt || [];(function() {var hm = document.createElement("script");hm.src = "https://hm.baidu.com/hm.js?8f9c5049cea1c960fa649821f6b1b2fb";var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(hm, s);})();<\/script>');
return this}})(jQuery,window,document);$(".back-top").hide();$(window).scroll(function(){200>=$(document).scrollTop()?$(".back-top").hide():$(".back-top").show();256>=$("body").height()-$(document).scrollTop()-$(window).height()&&$(".back-top").css({bottom:"256px"})});
